a=int(input("Enter integer 1:"))
b=int(input("ENTER INTEGER 2 :"))
print("Addition of integers : ",a+b)
print("Subtraction of integers : ",a-b)
print("Multiplication of integers : ",a*b)
print("Division of integers : ",a/b)
